apiVersion: v1
kind: Service
metadata:
  name: {{_variable_}}-service
spec:
  selector:
    app: {{_variable_}}
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  sessionAffinity: ClientIP
