apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{_variable_}}-network-policy
spec:
  podSelector:
    matchLabels:
      app: {{_variable_}}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: other
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: other
  policyTypes:
  - Ingress
  - Egress
