apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{gateway_name}}
  namespace: {{namespace}}
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      name: http
      number: 80
      protocol: HTTP
    hosts:
    - "{{host}}"
