gui:
  theme:
    activeBorderColor:
      - '#b4befe'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#b4befe'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'

  authorColors:
    '*': '#b4befe'

customCommands:
  - key: "o"
    command: "nvim -c ':Octo pr create'"
    context: "localBranches"
    loadingText: "Loading Octo"
    description: "Open pull request with Octo"
    subprocess: true
keybinding:
  branches:
    createPullRequest: "O"
