# Sourced by every zsh, interactive or not. Environment only: anything that
# prints, expects a TTY, or defines a widget belongs in .zshrc.

# Make path/fpath unique arrays so repeated sourcing cannot bloat them. Several
# things here prepend to PATH unconditionally (devops-cli's generated rc, nested
# tmux shells), and this makes all of that idempotent.
typeset -U path fpath

# --- editor ---------------------------------------------------------------
export EDITOR=nvim
export VISUAL=nvim
export KUBE_EDITOR=nvim
export PAGER=less
export LANG=en_US.UTF-8

# --- java -----------------------------------------------------------------
# Homebrew's openjdk is keg-only. Setting JAVA_HOME is enough for jdtls and
# maven, and avoids the sudo symlink into /Library/Java/JavaVirtualMachines
# that `brew info openjdk` suggests.
if [[ -d /opt/homebrew/opt/openjdk ]]; then
  export JAVA_HOME=/opt/homebrew/opt/openjdk
  path=("$JAVA_HOME/bin" $path)
fi

# --- path -----------------------------------------------------------------
path=(
  "$HOME/.local/bin"
  "$HOME/bin"
  $path
  "${KREW_ROOT:-$HOME/.krew}/bin"
)
[[ -d "$HOME/.cargo/bin" ]] && path+=("$HOME/.cargo/bin")

# --- ssh agent ------------------------------------------------------------
# Bitwarden desktop serves both ssh-nedsi-main and ssh-genesys from this socket,
# so there are no private keys on disk.
if [[ -S "$HOME/.bitwarden-ssh-agent.sock" ]]; then
  export SSH_AUTH_SOCK="$HOME/.bitwarden-ssh-agent.sock"
fi

# --- genesys tooling ------------------------------------------------------
# Both files are generated by the devops-cli installer. Never edit them; they
# get rewritten on update. .devopsclirc exports UV_TOOL_DIR / UV_TOOL_BIN_DIR
# and puts ~/.local/bin on PATH.
[[ -f "$HOME/.devopsclirc" ]] && source "$HOME/.devopsclirc"
[[ -f "$HOME/.devops_apps/dc_env/.rust/.cargo/env" ]] \
  && source "$HOME/.devops_apps/dc_env/.rust/.cargo/env"

# --- machine-local overrides ---------------------------------------------
# Untracked. Put work secrets and per-host environment here. Sourced early so
# its exports are visible to everything that follows, including .zshrc.
[[ -f "$HOME/.zshenv.local" ]] && source "$HOME/.zshenv.local"
